---
- name: "Move backend files to server."
  copy:
    src: /root/project/backend_artifact.tar.gz
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu
    tar -xzvf backend_artifact.tar.gz -C backend
    cd backend
    npm i && npm run build
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls
